name: King Arthur
on:
  workflow_dispatch:

jobs:
  sword-pulling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repos code
        uses: actions/checkout@v3

      - name: the excalibur
        env:
          THE_SECRET: ${{ secrets.RELEASE_KEYSTORE }}
        run: python thesecret.py